### PR TITLE
Debug Module v0.1

### PR DESCRIPTION
**Pull request by bluewww**
First release of debug module

### Added
- Parametrize buswidth to support 32-bit and 64-bit cores
- Support arbitrary base addresses in debug ROM
- Add misc helper functions to facilitate code generation
- Add README
- Fork from Ariane

### Changed
- Allow generic number of data registers
- Make JTAG IDCODE parametrizable

### Removed
- Remove ariane specific packages

### Fixed
- Fix resumeack and resumereq behaviour to be cleared and set according to debug
  specification
- Add missing JTAG test logic reset handling
- Fix resume logic in multihart situations
- Fix missing else(s) in system bus access
- Fix bad transitions into program buffer
- Fix error handling when using unsupported abstract commands
- Prevent harts from being in multiple states
- Fix various style issues

## Tests passed
* [x] riscv-tests/debug
* [x] OpenOCD compliance tests
* [x] PULPissimo sv testbench

### CODE REVIEW

**Comment by imphil** [comment]
Thanks for preparing a master-merge @bluewww! Would it be possible to incorporate the lint changes in #15 as well?

**Comment by bluewww** [comment]
Sure we can get those in too.

**Comment by imphil** [comment]
I've now opened #20 for the lint changes. Could you merge #20 and then soon merge pulpissimo_integration into master to get us out of this confusing branch scenario?

**Comment by imphil** [comment]
@bluewww do you have an ETA for merging this? (Just for my own planning.)

**Comment by bluewww** [comment]
I've been running my tests again and It didn't produce the same results as before I rebased so I was just making sure if its really ok. Turns out it is an irrelevant thing that timed out. I merge it now.

**Comment by imphil** [comment]
Thanks a lot @bluewww, your work is very much appreciated!

**Comment by bluewww** [comment]
Thank you for your help too @imphil

**Pull request merged**
