### PR TITLE
WIP: Add 32 bit debug support

### PR DESCRIPTION
**Pull request by zarubaf**

### CODE REVIEW

**Comment by zarubaf** [comment]
Lets try to push for a soonish `0.1` release.

I see the following things currently missing:

- [ ] Changelog entry for the things which have changed
- [ ] Factor out all the Ariane specific stuff, let's try not to duplicate the `riscv_pkg`
- [ ] README

**Comment by bluewww** [comment]
Regarding `riscv_pkg` how do you think we should handle it? If we remove it I have to add it to pulpissimo or RI5CY and maintain it there. Making a separate repository for such meta RISC-V defs seems overkills to me.

**Comment by zarubaf** [comment]
I would re-factor the package an remove all debug module related unnecessary things (like most CSRs, page-table structure, commit log features) and rename the package to something which is related to the debug module (so that the definitions don't clash with the original ones). Maybe we can even re-factor them to the already existing `dm_pkg`? Also I don't think that the `ariane_axi` package is needed anymore.

**Comment by bluewww** [comment]
Ok that sounds reasonable, I will do that. You might also want to move `ariane.cfg` into ariane.

**Comment by zarubaf** [comment]
Yes, you can safely delete this. I already have a copy in a different place. Thanks

**Pull request closed without merging**
