### PR TITLE
Add parameters in IP yml description for JG EDA tool

### PR DESCRIPTION
**Pull request by florent-gwt**

### CODE REVIEW

**Comment by bluewww** [comment]
I get this error when using this patch in PULPissimo:
```
ERROR: there are unallowed keys for ip 'fpu_div_sqrt_mvp', sub-ip 'div_sqrt_top_mvp':
    jg_slint_resets
    jg_slint_elab_opt
    jg_slint_clocks
    jg_slint_top_name
    jg_slint_postelab_cmds
Check the src_files.yml file.

```

**Comment by florent-gwt** [comment]
I need to add some authorized_keys in the main ipstools repo. We use a forked one, i forgot to back propagate my mods to the root repo

**Comment by florent-gwt** [comment]
https://iis-git.ee.ethz.ch/greenwaves-technologies/ipstools.git 
I find only this repo in eth github or gitlab. Is it the one you are using ? Please update it into HEAT of master branch please

**Comment by florent-gwt** [comment]
i pushed a fix in https://github.com/pulp-platform/IPApproX.git repo.

**Comment by bluewww** [comment]
Ok thanks looks good, seem to fix the breakage.

**Comment by bluewww** [comment]
See #35 and other PRs on `pulp-platform`. We don't add `jg` keys.

**Pull request closed without merging**
