### PR TITLE
32-bit slave access to Abstract Data

### PR DESCRIPTION
**Pull request by brabect1**
There are two flaws in present implementation of slave access (i.e. from CPU) to Abstract Data area:
* Writes do not work correctly with 32-bit access.
* Reads and writes do not work correctly for `dm::DataCount` other than two.

This pull request shows a possible fix. Not the prettiest code I wrote, but is fairly minimal in what it changes. It was tested only for 32-bit access and need to be verified for 64-bit one.

### CODE REVIEW

**Comment by bluewww** [comment]
What do you mean by "writes do not work correctly with 32-bit accesses"?

**Comment by bluewww** [comment]
Ok I think I see what you mean. Imo it's much easier to make `data_bits` to the same type as `data_i` (`[dm::DataCount-1:0][31:0]`) and then just add a for loop around this

```
                        for (int i = 0; i < $bits(be_i); i++) begin
                            if (be_i[i]) begin
                                data_bits[i*8+:8] = wdata_i[i*8+:8];
                            end
                        end
```
Did you consider this approach?

**Comment by brabect1** [comment]
This would not work only by itself, you need to bring in the `addr_i` address too. If you consider 32b bus, then `i` goes from 0 to 3 and your code can only change lowest 32 bits of `data_bits`. Just try it out. This becomes even more apparent when you go for `dm::DataCount` higher than two.

**Comment by bluewww** [comment]
Fixed in  #94

**Pull request closed without merging**
