### PR TITLE
Fix for SBA 'be' when reading (fixes #22).

### LINKED ISSUE #22: _be is stuck to 0 while reading
Shouldn't we have the same code as for the Write case regarding _be ?

### PR DESCRIPTION
**Pull request by jm4rtin**
Fixes #22 

@bluewww  It looks like you have a branch that addressed this with a copy & paste of the combinatorial logic but it never got merged in.

### CODE REVIEW

**Comment by bluewww** [comment]
I want to make this a parameter, so that we stay compatible with the current way we do it.

**Comment by jm4rtin** [comment]
Do you have a naming preference for this parameter? Perhaps _ReadByteEnable=1_ to default to the new behavior. Bring it out of dm_top with the other parameters?

**Comment by jm4rtin** [comment]
@bluewww I added a parameter at your request. Please review when you get a chance.

**Comment by bluewww** [comment]
Thanks for the PR Ill look into it

**Comment by bluewww** [comment]
Could you please make an entry in the CHANGELOG.md, then it is good to go.

**Comment by jm4rtin** [comment]
@bluewww Added to the changelog. Thanks for looking at it.

**Pull request merged**
